# **Clase 1 - Semana 5**

# Funciones

Una función es un conjunto de instrucciones que se agrupan para realizar una tarea específica, sirven para reutilizar códigos, organizar mejor los programas y evitar repetir instrucciones.

1. def	palabra clave para definir una función
2. parámetros	datos que la función recibe
3. return	indica qué valor devuelve la función
4. llamada	cuando usamos la función en el programa


In [ ]:
def sumar(a, b):  #una operación númerica (siempre la debemos llamar)
    resultado = a + b
    return resultado

In [ ]:
sumar(4324,234)

4558

In [ ]:
def resta(a,b):
    res = a - b
    return res

In [ ]:
resta(19, 27)

-8

Crear una función que convierta temperatura Celsius a Kelvin.

In [ ]:
def conversionC_K(T_C):
    res= T_C + 273.15
    return res

In [ ]:
conversionC_K(30)

303.15

Crear un afunción para convertir de bar a MPa

In [ ]:
def bar_MP(P_bar):
    res=P_bar * 0.1
    return res

In [ ]:
bar_MP(10)

1.0

# Uso de funciones para evaluar el estado termodinámico del agua

In [ ]:
def a_K (T, unidad):
  if unidad == "C":
      res= T + 273.15
      return res
  elif unidad == "F":
      res= (T - 32) * 5/9 + 273.15
      return res
  elif unidad == "R":
      res= T*5/9
      return res
  else:
    print("Dato no valido, verifique las unidades")

In [ ]:
a_K(25, "F")

269.26111111111106

In [ ]:
a_K(25, "h")

Dato no valido, verifique las unidades


In [ ]:
a_K (100, "R")

55.55555555555556

In [ ]:
def p_MPa(P, unidad):
    if unidad == "bar":
       res= P*0.1
       return res
    elif unidad == "mmHg":
      res = P / 7501
      return res
    elif unidad == "Psi":
       res = P / 145
       return res
    else:
      print("Dato no válido, verifique las unidades")

In [ ]:
p_MPa(10, "Psi")

0.06896551724137931

In [ ]:
def T_kelvin(T, unidad):
    if unidad == "C":
        return T + 273.15
    elif unidad == "F":
        return (T - 32)* 5/9 + 273.15
    elif unidad == "R":
        return T* 5/9
    elif unidad == "K":
        return T
    else:
       raise ValueError("Unidad de temperatura no válida. Usa C, F, R o K.")

In [ ]:
print(T_kelvin(25, "R"))

13.88888888888889


Conversiones P

In [ ]:
def P_MPa(P, unidad):
    if unidad == "bar":
        return P * 0.1
    elif unidad == "mmHg":
        return P/7501
    elif unidad == "Psi":
        return P / 145
    elif unidad == "atm":
        return P * 0.101325
    elif unidad == "MPa":
        return P
    else:
       raise ValueError("Unidad de Presión no válida. Usa bar, mmHg, Psi, atm o MPa")

In [ ]:
print(P_MPa(10, "mmHg"))

0.0013331555792560992


In [ ]:
def clasificar_estado(T_K, P_MPa):
    Tc = 647.1
    Pc = 22.06

    if T_K < Tc and P_MPa < Pc:
        return "Líquido o vapor"
    elif T_K > Tc and P_MPa > Pc:
        return "Supercrítico"
    elif T_K < Tc and P_MPa > Pc:
        return "Líquido comprimido"
    else:
        return "Cerca del punto crítico"

In [ ]:
clasificar_estado (250, 100)

'Líquido comprimido'

In [ ]:
T = float(input("Temperatura: "))
uT = input("Unidad (C, F, R o K): ")

P = float(input("Presión: "))
uP = input("Unidad (bar, mmHg, Psi, atm o MPa): ")

T_K = T_kelvin(T, uT)
P_MPa = P_MPa(P, uP)

print(clasificar_estado(T_K, P_MPa))

Temperatura: 25
Unidad (C, F, R o K): C
Presión: 4
Unidad (bar, mmHg, Psi, atm o MPa): bar
Líquido o vapor


# **Expresión Regular**

Una expresión regular es una secuencia de caracteres que define un patrón de búsqueda en cadenas de texto y se usa para buscar, validar, reemplazar o dividir texto de forma eficiente y flexible.

In [ ]:
capitales = ['#Ciudad Victo*ria', 'cuerna#vaca', 'Morelia!', 'xalapa', 'Tepic', 'hermos*illo',
 'toluca?', 'San? Luis Potosí', '*Mexicali', 'Villahermosa', 'Tuxtla Gutiérrez#',
 'Colima', 'la Paz#', 'Guadalajara', 'C*ampeche!', 'Durango', 'Zacatecas',
 '!Chetumal', 'Ciudad# de México', 'chilpancingo*', 'Chihua#hua', '?Aguascalientes',
 'Oaxaca de Juárez*', '?Puebla', 'Quer?étaro', 'Mérida', 'guanajuato',
 'pachu*ca', '#Saltillo#', 'Culiacán!', 'Tlaxcala', 'monterrey']

In [ ]:
import re #es la simplificación de la expresión regex

def limpiar_cadenas (strings):
  result = []
  for value in strings:
    value = value.strip()
    value = re.sub("[#*?!]", "", value)
    value = value.title()
    result.append (value)
  return result

In [ ]:
limpiar_cadenas (capitales) #entre parentesis siempre va la orden a realizar

['Ciudad Victoria',
 'Cuernavaca',
 'Morelia',
 'Xalapa',
 'Tepic',
 'Hermosillo',
 'Toluca',
 'San Luis Potosí',
 'Mexicali',
 'Villahermosa',
 'Tuxtla Gutiérrez',
 'Colima',
 'La Paz',
 'Guadalajara',
 'Campeche',
 'Durango',
 'Zacatecas',
 'Chetumal',
 'Ciudad De México',
 'Chilpancingo',
 'Chihuahua',
 'Aguascalientes',
 'Oaxaca De Juárez',
 'Puebla',
 'Querétaro',
 'Mérida',
 'Guanajuato',
 'Pachuca',
 'Saltillo',
 'Culiacán',
 'Tlaxcala',
 'Monterrey']

In [ ]:
capitales_limpias = limpiar_cadenas (capitales)

capitales_limpias.sort() #sort para ordenar en orden alfabético

In [ ]:
capitales_limpias

['Aguascalientes',
 'Campeche',
 'Chetumal',
 'Chihuahua',
 'Chilpancingo',
 'Ciudad De México',
 'Ciudad Victoria',
 'Colima',
 'Cuernavaca',
 'Culiacán',
 'Durango',
 'Guadalajara',
 'Guanajuato',
 'Hermosillo',
 'La Paz',
 'Mexicali',
 'Monterrey',
 'Morelia',
 'Mérida',
 'Oaxaca De Juárez',
 'Pachuca',
 'Puebla',
 'Querétaro',
 'Saltillo',
 'San Luis Potosí',
 'Tepic',
 'Tlaxcala',
 'Toluca',
 'Tuxtla Gutiérrez',
 'Villahermosa',
 'Xalapa',
 'Zacatecas']

# **Programación orientada a arrays**

**¿Qué es un array?**
Un array es una estructura de datos que sirve para guardar varios valores en una sola variable, a diferencia de una variable común que solo puede guardar un dato, *un array puede guardar una colección de datos del mismo tipo*, pueden ser varios números o varias palabras

Calificaciones de alumnos

In [ ]:
calif1 = 8.5
calif2 = 9.0
calif3 = 7.5
calif4 = 10.0
calif5 = 8.0

In [ ]:
cal = [8.5, 9.0, 7.5, 10.0, 8.0] #es mejor guardarlos entre corchetes para tenerlos mas ordenados
cal

[8.5, 9.0, 7.5, 10.0, 8.0]

In [ ]:
valores = [1, 2, 3, 4] #es una colección de datos guardados en una sola variable

In [ ]:
import numpy as np

a = np.array([1, 2, 3]) #vector

b = np.array([[1, 2, 3], #matriz
              [4, 5, 6]])

In [ ]:
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

np.int64(32)

In [ ]:
A = np.array([
    [2, 4, 6],
    [4, 5, 7],
    [6, 7, 9]
])

B = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

In [ ]:
A, B

(array([[2, 4, 6],
        [4, 5, 7],
        [6, 7, 9]]),
 array([[1, 2, 3],
        [0, 1, 4],
        [5, 6, 0]]))

In [ ]:
producto= np.dot(A, B)
print(producto)

[[32 44 22]
 [39 55 32]
 [51 73 46]]


Suma/resta de matrices

In [ ]:
C= A + B
C

array([[ 3,  6,  9],
       [ 4,  6, 11],
       [11, 13,  9]])

In [ ]:
A.T #A.T es Array Technology

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [ ]:
np.array_equal(A, A.T) #sirve para comparar entre los valores si dan true or false

True

**Determinante**

In [ ]:
np.linalg.det(A)

np.float64(3.9999999999999867)

# **Inversa de una matriz**

In [ ]:
B_i = np.linalg.inv(B)
B_i

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [ ]:
np.dot(B, B_i).round() #sirve para redondear valores

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [ ]:
A=np.array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])
A

array([[2, 4, 6],
       [4, 5, 7],
       [6, 7, 9]])

In [ ]:
np.mean(A)

np.float64(5.555555555555555)

**Funciones rápidas de array**

In [ ]:
arr = np.arange(1,12) #una serie continua solo los valores dentro de la secuencia
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.log(arr) #para calcular la base

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527])

In [ ]:
np.exp(arr) #para calcular la salida

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

# **Sistema de ecuaciones**

Resolver la siguiente ecuación:

2x1+4x2+6x3=18,

4x1+5x2+6x3=24,

3x1+x2-2x3=4

In [ ]:
A = np.array([[2, 4, 6],
              [4, 5, 6],
              [3, 1, -2]])

In [ ]:
D=np.linalg.det(A) #D para calcular la determinante
D

np.float64(5.999999999999996)

Crea matrices modificadas para cada variable

Para encontrar X: reemplaza la primera columna de A con el vector de términos independientes.
Para encontrar Y: reemplaza la segunda columna
Para encontrar Z: reemplaza la tercera columna (y así sucesivamente)

In [ ]:
X = np.array([[18,4,6],
               [24, 5,6],
               [4, 1, -2]])

Calcula el determinante de cada matriz modificada
Dx, Dy, Dz,

In [ ]:
Dx = np.linalg.det(X)
Dx

np.float64(24.000000000000004)

Aplica la fórmula de Cramer

1.   x = Dx/D
2.   y = Dy/D
3.   z = Dz/D

In [ ]:
x = Dx/D
x

np.float64(4.0000000000000036)

In [ ]:
b = np.array([18,24,4])

x=np.linalg.solve(A, b)

In [ ]:
np.dot(A,x)

array([18., 24.,  4.])

# **Ejercicio - Sistema 8x8**

In [ ]:
A = np.array([
    [1, 2, 1, 1, 1, 1, 1, 1],
    [1, 1, 2, 1, 1, 1, 1, 1],
    [1, 1, 1, 2, 1, 1, 1, 1],
    [1, 1, 1, 1, 2, 1, 1, 1],
    [1, 1, 1, 1, 1, 2, 1, 1],
    [1, 1, 1, 1, 1, 1, 2, 1],
    [1, 1, 1, 1, 1, 1, 1, 2],
    [2, 1, 1, 1, 1, 1, 1, 1]
], dtype=float) #matriz de coeficientes

In [ ]:
b = np.array([16, 15, 14, 13, 12, 11, 10, 17], dtype=float) #para calcular vectores

In [ ]:
x=np.linalg.solve(A, b)
x

array([ 5.00000000e+00,  4.00000000e+00,  3.00000000e+00,  2.00000000e+00,
        1.00000000e+00, -7.13714802e-17, -1.00000000e+00, -2.00000000e+00])

In [ ]:
np.dot(A,x)

array([16., 15., 14., 13., 12., 11., 10., 17.])

# **Números aleatorios**

La función randrange(a, b, salto) genera números enteros aleatorios comprendidos entre a y b separados entre sí con un salto.

In [ ]:
rng = np.random.default_rng(seed=123) #el argumento seed determina el estado inicial del generador

arr = rng.standard_normal((5, 4))

In [ ]:
arr #arr simplificado de array

array([[-0.98912135, -0.36778665,  1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379, -0.63646365,  0.54195222],
       [-0.31659545, -0.32238912,  0.09716732, -1.52593041],
       [ 1.1921661 , -0.67108968,  1.00026942,  0.13632112],
       [ 1.53203308, -0.65996941, -0.31179486,  0.33776913]])

In [ ]:
import random as rd

In [ ]:
for i in range(8):
    print(rd.randrange(5, 200, 2))

57
17
31
49
151
31
183
41


In [ ]:
for i in range(11):
    print(rd.random())

0.17995308036594793
0.3910192388385274
0.9200051947092578
0.7805237070772966
0.7100312969223164
0.88657104774058
0.007647642366264029
0.837246684724772
0.5757809651793593
0.8090098680368141
0.6198239975745835


In [ ]:
frutas = ["peras", "manzanas", "plátanos", "ciruelas","mangos"]

for i in range(8):
    print(rd.choice(frutas)) #choice() devuelve un elemento aleatorio de una lista

ciruelas
mangos
plátanos
manzanas
plátanos
peras
manzanas
peras


In [ ]:
rd.choice(frutas)

'manzanas'